name: docker-hub

on:
 push:
   branches:
   - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@master
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: tencentcom/tencentcloud-cli:latest      
      
